--[[
LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
--]]

local lcm = require('lcm')

local lcmtest_primitives_t = require('lcmtest.primitives_t')
local lcmtest2_another_type_t = require('lcmtest2.another_type_t')

local setmetatable = setmetatable
local ipairs = ipairs
local table = table
local string = string
local unpack = unpack

-- buffer helper for decoding
local _buffer_helper = {}
_buffer_helper.__index = _buffer_helper

function _buffer_helper:new(data_str)

  local obj = {buffer = data_str, index = 1}
  setmetatable(obj, self)

  return obj
end

function _buffer_helper:read(n_bytes)

  local partial = self.buffer:sub(self.index, self.index + n_bytes - 1)
  self.index = self.index + n_bytes

  if self.index > #self.buffer + 1 then
    error('buffer ran out of bytes')
  end

  return partial
end

local cross_package_t = {}
cross_package_t.__index = cross_package_t

cross_package_t.name = 'lcmtest2.cross_package_t'
cross_package_t.packagename = 'lcmtest2'
cross_package_t.shortname = 'cross_package_t'

function cross_package_t:new()

  local obj = {}

  obj.primitives = nil
  obj.another = nil

  setmetatable(obj, self)

  return obj
end

function cross_package_t._get_hash_recursive(parents)

  local newparents = {}

  for _, v in ipairs(parents) do
    if v == cross_package_t then return lcm._hash.new('0x0') end
    table.insert(newparents, v)
  end

  table.insert(newparents, cross_package_t)

  local hash = lcm._hash.new('0xbbd3dd8a23ec1955')
    + lcmtest_primitives_t._get_hash_recursive(newparents)
    + lcmtest2_another_type_t._get_hash_recursive(newparents)
  hash:rotate(1)

  return hash
end

cross_package_t._packed_fingerprint = lcm._pack.pack('>X', cross_package_t._get_hash_recursive({}))

function cross_package_t:encode()

  return cross_package_t._packed_fingerprint .. self:_encode_one()
end

function cross_package_t:_encode_one()

  local buf_table = {}

  table.insert(buf_table, self.primitives:_encode_one())
  table.insert(buf_table, self.another:_encode_one())

  return table.concat(buf_table)
end

function cross_package_t.decode(data)

  if data:sub(1, 8) ~= cross_package_t._packed_fingerprint then
    error('bad fingerprint')
  end

  return cross_package_t._decode_one(data:sub(9))
end

function cross_package_t._decode_one(data)

  if not data.read then
    data = _buffer_helper:new(data)
  end

  local obj = cross_package_t:new()

  obj.primitives = lcmtest_primitives_t._decode_one(data)
  obj.another = lcmtest2_another_type_t._decode_one(data)

  return obj
end

return cross_package_t

